# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GPM
                                 A QGIS plugin
 GPM Plugin 2to3 test
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2019-10-07
        copyright            : (C) 2019 by Hermesys
        email                : mhcho058@hermesys.co.kr
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load GPM class from file GPM.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .GPM import GPM

    return GPM(iface)
