# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'about.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from qgis.PyQt import QtCore, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(554, 291)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.btn_Open_Manual = QtWidgets.QPushButton(Dialog)
        self.btn_Open_Manual.setObjectName("btn_Open_Manual")
        self.verticalLayout.addWidget(self.btn_Open_Manual)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(
            _translate("Dialog", "KICT Satellite Precipitation Converter")
        )
        self.label.setText(
            _translate(
                "Dialog",
                "\n"
                "        Copyright\n"
                "        Copyright © 2018 HermeSys Co., Ltd. All rights reserved.\n"
                "\n"
                "        Restricted Rights Legend\n"
                "        이 프로그램과 문서는 ㈜헤르메시스 라이선스 동의 하에서 편집될 수 있습니다.\n"
                "        사용,복사,인쇄,인용은 동의없이 자유롭게 가능합니다.\n"
                "\n"
                "        헤르메시스\n"
                "        (11801) 경기도 의정부시 문화로 10, 고산듀클래스 903호\n"
                "        TEL:031-837-7102\n"
                "        Homepage: http://www.hermesys.co.kr\n"
                "      ",
            )
        )
        self.btn_Open_Manual.setText(_translate("Dialog", "User’s Manual"))
